18MAR20 Update 3
Got it to work as hoped, but as soon as I added a third agent, it broke the model again.

Traceback (most recent call last):

  File "C:\Users\Chris\Google Drive\GitHub\ABM-Project\run.py", line 11, in <module>
    model = Model(5,5)

  File "C:\Users\Chris\Google Drive\GitHub\ABM-Project\Model.py", line 57, in __init__
    agent1b = Agent1B(self.next_id(),(x,y), self, True)

TypeError: __init__() takes 3 positional arguments but 5 were given